"""
Helpers for exporting an Excel workbook to PDF on macOS via AppleScript.
Only the first worksheet is exported (on a duplicated workbook), preserving A1/K1 and formats.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
import shutil
from pathlib import Path
from textwrap import dedent


def export_first_sheet_to_pdf(xlsx_path: str | Path, pdf_path: str | Path | None = None) -> Path:
    """
    Exports the first worksheet of an Excel file to PDF using AppleScript (macOS only).

    The source workbook is duplicated to a temporary copy (formats and A1/K1 preserved),
    then sheets 2..n are removed on the copy before exporting it to PDF. The source
    workbook remains untouched.

    Args:
        xlsx_path: path to the Excel file to export.
        pdf_path: optional output PDF path. If omitted, uses same stem as the Excel file.

    Returns:
        Path to the generated PDF.
    Raises:
        RuntimeError if export fails or platform is not macOS.
    """
    if sys.platform != "darwin":
        raise RuntimeError("AppleScript export is only supported on macOS.")

    xlsx = Path(xlsx_path).expanduser().resolve()
    if pdf_path:
        pdf = Path(pdf_path).expanduser().resolve()
    else:
        pdf = xlsx.with_suffix(".pdf")

    # Duplicate workbook to avoid altering the source
    tmp_dir = Path(tempfile.gettempdir())
    tmp_copy = tmp_dir / (xlsx.stem + "_pdf_tmp.xlsx")
    shutil.copy2(xlsx, tmp_copy)

    script = dedent(
        f"""
        set theFile to POSIX file "{tmp_copy}"
        set pdfFile to POSIX file "{pdf}"
        set hfsPath to (theFile as alias as string)

        tell application "Microsoft Excel"
            activate
            set display alerts to false
            set wbSource to open workbook workbook file name hfsPath
            -- préserver A1 et K1 en valeurs (pour éviter #REF! après suppression des autres feuilles)
            set valA to value of range "A1" of worksheet 1 of wbSource
            set value of range "A1" of worksheet 1 of wbSource to valA
            set valK to value of range "K1" of worksheet 1 of wbSource
            set value of range "K1" of worksheet 1 of wbSource to valK
            repeat while (count of worksheets of wbSource) > 1
                delete worksheet 2 of wbSource
            end repeat
            save wbSource in pdfFile as PDF file format
            close wbSource saving no
            set display alerts to true
        end tell
        """
    )

    res = subprocess.run(
        ["osascript", "-e", script],
        capture_output=True,
        text=True,
    )
    if res.returncode != 0:
        raise RuntimeError(f"AppleScript export failed: {res.stderr or res.stdout}")

    if not pdf.exists():
        raise RuntimeError("PDF not generated by Excel.")

    # Cleanup temp copy
    try:
        if tmp_copy.exists():
            tmp_copy.unlink()
    except Exception:
        pass

    return pdf
