name: Build ASF Scheduler

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: electron_app
        run: npm install

      - name: Build
        working-directory: electron_app
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            npm run build-mac
          else
            npm run build-win
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ASF-Scheduler-${{ matrix.os }}
          path: electron_app/dist/*
